//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.LF.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_logs
    {
        public int email_log_id { get; set; }
        public int request_id { get; set; }
        public string sent_to { get; set; }
        public string subject { get; set; }
        public Nullable<System.DateTime> sent_at { get; set; }
        public string status { get; set; }
    
        public virtual location_requests location_requests { get; set; }
    }
}
