//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.LF.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public int location_id { get; set; }
        public int request_id { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<double> accuracy { get; set; }
        public Nullable<System.DateTime> captured_at { get; set; }
        public string device_info { get; set; }
        public string ip_address { get; set; }
    
        public virtual location_requests location_requests { get; set; }
    }
}
